### ISSUE TITLE
Genres

### ISSUE THREAD

**Issue by VirtuaBoza** [tommcgurl/choose-your-own-adventure-builder#25]
Spitballing:
Fantasy
Sci-Fi
Horror
Mystery/Thriller
Action/Adventure
Romance
Historical Fiction

Should probably be more generic and allow just one genre selection (but multiple tags)

**Comment by warpfox** [comment]
@VirtuaBoza and I created a list of set Genres that can be selected from the Editor to add to an adventure. Selecting a Genre for an adventure is not required when it's a draft, but will be required in order to publish the adventure.

In the Reader, genres are now visible on each adventure's "card" to show the user which genre the adventure belongs to.
